
#ifndef __KTX_LOADER_H__
#define __KTX_LOADER_H__ 1

namespace SE {

/**
 * Load strategy: load a KTX1 cubemap from a .ktx file into TextureStock.
 *
 * Supports KTX1 files with 6 faces (cubemaps) and any number of mip levels.
 * Compatible with files generated by cmgen (Filament):
 *   cmgen -f ktx --extract <dir> input.exr   → 1-mip irradiance cubemap
 *   cmgen -f ktx --ibl-ld   <dir> input.exr  → N-mip prefiltered specular
 *
 * After Load(), the following TextureStock fields are populated:
 *   format, internal_format, gl_type  — from KTX1 header
 *   width, height                     — base-level dimensions
 *   num_faces (always 6), num_mips
 *   raw_image                         — pointer to the KTX data section
 *   vOwnedData                        — owns the raw file bytes
 */
class KTXLoader {

public:
        struct Settings {};
        typedef Settings TChild;

        KTXLoader(const Settings & oSettings);
        ret_code_t Load(const std::string & sPath, TextureStock & oTextureStock);
};

} // namespace SE
#endif
