
#ifndef STORE_TEXTURE_CUBE_MAP_H
#define STORE_TEXTURE_CUBE_MAP_H 1

#include <string>
#include <glm/vec3.hpp>

namespace SE {

class StoreTextureCubeMap {

public:
        struct Settings {
                std::string path_prefix;  // empty → use solid_color
                glm::vec3   solid_color { 0.f, 0.f, 0.f };
                int32_t     min_filter  { GL_LINEAR_MIPMAP_LINEAR };
                int32_t     mag_filter  { GL_LINEAR };

                // Load 6 PNG faces: {prefix}px/nx/py/ny/pz/nz.png
                // flip_vertically: set true only if the source images are stored top-left
                // origin and were NOT generated by an OpenGL-aware tool (e.g. cmgen outputs
                // faces already in the correct OpenGL orientation — no flip needed).
                bool        flip_vertically { false };

                explicit Settings(const std::string & prefix,
                                  int32_t min_f = GL_LINEAR_MIPMAP_LINEAR,
                                  int32_t mag_f = GL_LINEAR,
                                  bool    flip  = false)
                        : path_prefix(prefix), min_filter(min_f), mag_filter(mag_f),
                          flip_vertically(flip) {}

                // Create 1×1 solid-colour cubemap (for default/fallback)
                explicit Settings(glm::vec3 color)
                        : solid_color(color), min_filter(GL_LINEAR), mag_filter(GL_LINEAR) {}

                // Data comes from TextureStock (KTX path via KTXLoader).
                Settings() = default;
        };

        typedef Settings TChild;

private:
        const Settings & oSettings;

public:
        StoreTextureCubeMap(const Settings & s);
        ret_code_t Store(const TextureStock & oTextureStock, uint32_t & id, uint32_t & gl_type);
};

} // namespace SE
#endif
